### ISSUE TITLE
Validate `address` argument

### ISSUE THREAD

**Issue by kseo** [CodeChain-io/codechain-keystore-cli#11]
Check if the given address is well-formed.

**Comment by majecty** [comment]
We can use the SDK's `PlatformAddress.fromString` as a validation function.
See https://github.com/CodeChain-io/codechain-faucet/blob/2e0f87726f28f0d9f072d683a9a8f2efb40922c2/logic/index.ts#L101

**Comment by redongjun** [comment]
@majecty First, I will use the `PlatformAddress.fromString` function mentioned.

Later, it would be better to change the `PlatformAddress.check` function when the SDK is updated.
https://github.com/CodeChain-io/codechain-sdk-js/blob/9841898872e6d487dedc052f737e997002859e22/src/key/PlatformAddress.ts#L89
